In [16]:
import numpy as np
import pandas as pd
from pyfixest.estimation import feols
from pyfixest.utils import get_data
from pyfixest.summarize import etable
data = get_data()
data['compliance'] = data['X1']
data['treatment_assignment'] = data['Z1']
data.head()

,Y,Y2,X1,X2,f1,f2,f3,group_id,Z1,Z2,weights,compliance,treatment_assignment
0,NaN,2.357103,0.0,0.457858,15.0,0.0,7.0,9.0,-0.330607,1.054826,0.661478,0.0,-0.330607
1,-1.458643,5.163147,NaN,-4.998406,6.0,21.0,4.0,8.0,NaN,-4.113690,0.772732,NaN,NaN
2,0.169132,0.751140,2.0,1.558480,NaN,1.0,7.0,16.0,1.207778,0.465282,0.990929,2.0,1.207778
3,3.319513,-2.656368,1.0,1.560402,1.0,10.0,11.0,3.0,2.869997,0.467570,0.021123,1.0,2.869997
4,0.134420,-1.866416,2.0,-3.472232,19.0,20.0,6.0,14.0,0.835819,-3.115669,0.790815,2.0,0.835819

In [19]:
fit_iv = feols("Y ~ 1 | compliance ~ treatment_assignment", data = data).vcov('hetero')
etable([fit_iv])

                           est1
------------  -----------------
depvar                        Y
-------------------------------
Intercept      0.933*** (0.154)
compliance    -1.014*** (0.134)
-------------------------------
-------------------------------
R2                            -
S.E. type                hetero
Observations                998
-------------------------------
Significance levels: * p < 0.05, ** p < 0.01, *** p < 0.001